version: '3'

services:
  postgres:
    image: postgres:12.3-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}

  backend:
    depends_on:
      - postgres
    build: src
    restart: always
    ports:
      - "443:443"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      client_id: ${client_id}
      client_secret: ${client_secret}
      redirect_uri: ${redirect_uri}
      LinkRedirect: ${LinkRedirect}
      state: ${state}
      JWT_SECRET: ${JWT_SECRET}
      MAX_PROFILE_PICTURE_SIZE_IN_BYTES: ${MAX_PROFILE_PICTURE_SIZE_IN_BYTES}


# Delete debug code

# 42 API and other redirects need to got to https://url:443

# Volumes are not implemented
