version: '3'

services:
  postgres:
    image: postgres:12.3-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: team-zero

  backend:
    depends_on:
      - postgres
    build: ft_transcendence
    restart: always
    ports:
      - "443:443"

# ENV is not implemented

# import * as fs from 'fs';
#   const app = await NestFactory.create(AppModule, {
#     httpsOptions: {
#       key: fs.readFileSync(`/keys/key.key`),
#       cert: fs.readFileSync(`/keys/key.pem`),
#     }
#   });
