version: '3'

services:
  postgres:
    image: postgres:12.3-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: team-zero

  backend:
    depends_on:
      - postgres
    build: src
    restart: always
    ports:
      - "443:443"

# Delete debug code

# 42 API and other redirects need to got to https://url:443

# ENV is not implemented

# Volumes are not implemented
