version: '3'

# volumes:
#   source_code:
#     driver: local
#     name: source_code
#     driver_opts:
#       type: none
#       o: bind
#       device: /Users/rdrazsky/Desktop/Work/pong/src

services:
  ft_transcendence:
    build: ./
    # restart: always
    ports:
      - "80:80"
      - "5432:5432"
      - "53603:53603"
    volumes:
      - /Volumes/Storage/goinfre/bhoitzin/GitHub/ft_transcendence/pong:/server
    # environment:
