setup:
	npm i --save @nestjs/common
	npm i --save @nestjs/core
	npm i --save @nestjs/config
	npm i --save @nestjs/typeorm typeorm mysql2
	npm i --save class-validator
	npm i --save pg
	npm i --save @types/react @types/react-dom
	npm i -—save react-scripts
	npm i --save react-shapes
	npm i --save-dev web-vitals
	npm i --save typescript
	npm add bcrypt
	npm add @nestjs/jwt @nestjs/passport passport passport-jwt
	npm audit fix

# create project: npx create-react-app my-app --template typescript
