setup:
	npm i -—save react-scripts
	npm i --save @types/react @types/react-dom
	npm i --save react-shapes
	npm i web-vitals --save-dev
	npm audit fix

# create project: npx create-react-app my-app --template typescript
